mysite/Search/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

urlpatterns=[
    path('tagSearch/<int:id>/', views.tagSearch, name="tag_search"),
    path('absoluteSearch/', views.absoluteSearch, name="absolute_search"),
]

mysite/mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('admin/', admin.site.urls),
    path('main/', include('CourseProject.urls'), name="home_page"),
    path('authentication/', include('authentication.urls')),
    path('accounts/', include('allauth.urls')),
    path('feedback/', include('Feedback.urls')),
    path('search/', include('Search.urls')),
    url(r'^messages/', include('postman.urls', namespace='postman')),
]

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]
#
# urlpatterns += i18n_patterns(
#     path('admin/', admin.site.urls),
#     path('main/', include('CourseProject.urls')),
#     path('authentication/', include('authentication.urls')),
#     path('accounts/', include('allauth.urls')),
#     prefix_default_language=True,
# )

mysite/CourseProject/models.py
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Avg
# from Search.search import ArticleIndex


class Article(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True)
    shortDescription = models.TextField(blank=True, null=True)
    specialityNumber = models.CharField(max_length=20, blank=True, null=True)
    mainText = models.TextField(blank=True, null=True)
    creationDate = models.DateTimeField(blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    likes = models.ManyToManyField(User, related_name='likes', blank=True)

    def get_rating_for_article(self):
        return self.rating_set.filter(article_id=self.id).aggregate(Avg('starCount'))

    def indexing(self):
        from Search.search import ArticleIndex
        obj = ArticleIndex(
            meta={'id': self.id},
            mainText=self.mainText,
            shortDescription=self.shortDescription,
            name=self.name,
            specialityNumber=self.specialityNumber
        )
        obj.save()
        return obj.to_dict(include_meta=True)
    # def indexing(self):
    #     from Search.search import ArticleIndex
    #     obj = ArticleIndex(meta={'id': self.id}, name=self.name, creationDate=self.creationDate,
    #                        shortDescription=self.shortDescription, specialityNumber=self.specialityNumber)
    #     return obj.to_dict(include_meta=True)

class Tag(models.Model):
    text = models.CharField(max_length=20)
    article = models.ManyToManyField(Article)

class LikeForArticle(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Rating(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    starCount = models.IntegerField()

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    creationDate = models.DateTimeField()

    def get_likes_for_comment(self):
        return self.likeforcomment_set.filter(comment_id=self.id).count()

class LikeForComment(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

mysite/Search/models.py
from django.db import models

# Create your models here.

mysite/Search/views.py
from django.shortcuts import render
# from Search.documents import ArticleDocument
from django.apps import apps
from elasticsearch_dsl import DocType, Text, Date, Search
Rating = apps.get_model('CourseProject', 'Rating')
Tag = apps.get_model('CourseProject', 'Tag')

def tagSearch(request, id):
    tags = Tag.objects.filter(id__icontains=id)
    data = {"user": request.user,
            "rating": Rating.objects.all(),
            "tags": tags}
    return render(request, 'search/tagSearch.html', context=data)

def absoluteSearch(request):
    s = Search().filter('term', name=request.GET.get('q'))
    response = s.execute()
    return render(request, 'search/search.html', { "articles": response, "user": request.user, "rating": Rating.objects.all() })


# def search(name):
#     s = Search().filter('term', name=name)
#     response = s.execute()
#     print(response[0].mainText)
#
#     return response

# def search(request):
#     from Search.search import ArticleIndex
#     posts = ArticleIndex.search().query("match", title="test")
#
#     return posts.execute()


#     q = request.GET.get('q')
#     # if q:
#     articles = ArticleDocument.search().query("match", title=q)
#     # else:
#     #     articles = ''
#
#     return render(request, 'search/search.html', {"articles": articles})

mysite/Search/templates/search/search.html
{% extends "CourseProject/wrapper.html"%}
{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!--<script src="/static/js/uploadImage.js"></script>-->
<script src='https://cloud.tinymce.com/stable/tinymce.min.js'></script>
<script>
  tinymce.init({
    selector: '#mytextarea'
  });
</script>

<script type="text/javascript">
$(document).ready(function(event){
    $(document).on('click', '#like', function(event){
        event.preventDefault();
        var pk = $(this).attr('value');
        $.ajax({
            type: 'POST',
            url: '{% url "like_post" %}',
            data: {'id': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
            dataType: 'json',
            success: function(response){
                $('#like-section').html(response['form'])
                console.log($('#like-section').html(response['form']));
            },
            error: function(rs, e){
                console.log(rs.responseText);
            }
        });
    });
});
</script>

{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}


<div style="float:right; width: 330px; margin-right:100px;">
    <div style="position: sticky; top: 0; min-height: 2em;" class="card mb-4 shadow-sm">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{% trans "Пользователь" %}</h4>
        </div>
        <div class="card-body" style="background: white;">
            <ul class="list-unstyled mt-3 mb-4">
                <!--<li>-->
                <!--<button class="btn btn-default" type="submit"><a href="{% url 'register' %}">Регистрация</a>-->
                <!--</button>-->
                <!--</li>-->
                <li>
                    <!--<form action="{% url 'register' %}">-->
                    <a href="{% url 'signup' %}">
                        <button type="button" type="submit" class="btn btn-lg btn-block btn-outline-primary">
                            {% trans "Зарегистрироваться" %}
                        </button>
                    </a>
                    <!--</form>-->
                </li>
                <br>
                <li><a href="{% url 'login' %}">
                    <button type="button" type="submit" class="btn btn-lg btn-block btn-outline-primary">{% trans "Войти" %}</button>
                </a></li>
                <br>
                <li><a href="{% url 'logout' %}">
                    <button type="button" type="submit" class="btn btn-lg btn-block btn-outline-primary">{% trans "Выйти" %}</button>
                </a></li>
            </ul>
            <!--<button type="button" class="btn btn-lg btn-block btn-outline-primary">Sign in</button>-->
        </div>
            <div id="tag-section" >
        {% include "feedback/tag_section.html" %}
    </div>
    </div>

    <div style="height:1000px;">

    </div>
</div>


<div style="width:1200px;" class="container">
    {% for item in articles %}

    <div style="float:left; width: 770px;">
        <div style="padding-top:10px; width:1200px;" class="container">
            <div style="padding-left:0px;" class="col">
                <!--<div id="like-section">-->
                <!--{% include "feedback/like_section.html" %}-->
                <!--</div>-->
                <div class="likeBlock">
                    <p>&#x25B2</p>

                    <!--<p style="font-size:12px;">{{ item.likes.count }}</p>-->
                    <p>&#x25BC</p>
                </div>
                <div onclick="location.href='/main/view/{{ item.meta.id }}'" class="card mb-4 shadow-sm clickableBlock">
                    <h1 style="width:98%; margin:auto"><a class="text" href="#">{{ item.name }}</a></h1>
                    <!--<img class="card-img-top" alt="Thumbnail [100%x225]"-->
                         <!--style="height: auto; width: 98%; display: block; margin:auto;"-->
                         <!--src="https://millionstatusov.ru/pic/statpic/all/58e61335ec518.jpg" data-holder-rendered="true">-->
                    <div class="card-body">
                        <div id="forSave" style="max-height:180px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">
                            <p class="card-text">{{ item.mainText|safe }}</p>
                        </div>

                        <br>
                        <br>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">{% trans "комментировать" %}</button>

                            </div>
                            <small class="text-muted">{{item.creationDate}}</small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% endblock %}

mysite/Search/templates/search/tagSearch.html
{% extends "CourseProject/wrapper.html"%}
{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src='https://cloud.tinymce.com/stable/tinymce.min.js'></script>
<script>
  tinymce.init({
    selector: '#mytextarea'
  });


</script>
<script type="text/javascript">
$(document).ready(function(event){
    $(document).on('click', '#like', function(event){
        event.preventDefault();
        var pk = $(this).attr('value');
        $.ajax({
            type: 'POST',
            url: '{% url "like_post" %}',
            data: {'id': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
            dataType: 'json',
            success: function(response){
                $('#like-section').html(response['form'])
                console.log($('#like-section').html(response['form']));
            },
            error: function(rs, e){
                console.log(rs.responseText);
            }
        });
    });
});


</script>

{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<div style="float:right; width: 330px; margin-right:100px;">
    <div style="position: sticky; top: 0; min-height: 2em;" class="card mb-4 shadow-sm">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{% trans "Пользователь" %}</h4>
        </div>
        <div class="card-body" style="background: white;">
            <ul class="list-unstyled mt-3 mb-4">
                <!--<li>-->
                <!--<button class="btn btn-default" type="submit"><a href="{% url 'register' %}">Регистрация</a>-->
                <!--</button>-->
                <!--</li>-->
                <li>
                    <!--<form action="{% url 'register' %}">-->
                    <a href="{% url 'signup' %}">
                        <button type="button" type="submit" class="btn btn-lg btn-block btn-outline-primary">
                            {% trans "Зарегистрироваться" %}
                        </button>
                    </a>
                    <!--</form>-->
                </li>
                <br>
                <li><a href="{% url 'login' %}">
                    <button type="button" type="submit" class="btn btn-lg btn-block btn-outline-primary">{% trans "Войти" %}</button>
                </a></li>
                <br>
                <li><a href="{% url 'logout' %}">
                    <button type="button" type="submit" class="btn btn-lg btn-block btn-outline-primary">{% trans "Выйти" %}</button>
                </a></li>
            </ul>
            <!--<button type="button" class="btn btn-lg btn-block btn-outline-primary">Sign in</button>-->
        </div>
            <div id="tag-section" >
        {% include "feedback/tag_section.html" %}
    </div>
    </div>

    <div style="height:600px;">

    </div>
</div>

<div style="width:1200px;" class="container">
    {% if tags.count > 0 %}
    {% for tag in tags %}
    {% for item in tag.article.all %}
    <div style="float:left; width: 770px;">
        <div style="padding-top:10px; width:1200px;" class="container">
            <div style="padding-left:0px;" class="col">
                <!--<div id="like-section">-->
                <!--{% include "feedback/like_section.html" %}-->
                <!--</div>-->
                <div class="likeBlock">
                    <p>&#x25B2</p>
                    <p style="font-size:12px;">{{ item.get_rating_for_article.starCount__avg }}</p>
                    <!--<p style="font-size:12px;">{{ item.likes.count }}</p>-->
                    <p>&#x25BC</p>
                </div>
                <div onclick="location.href='../../../main/view/{{ item.id }}'" class="card mb-4 shadow-sm clickableBlock">
                    <h1 style="width:98%; margin:auto"><a class="text" href="#">{{ item.name }}</a></h1>
                    <img class="card-img-top" alt="Thumbnail [100%x225]"
                         style="height: auto; width: 98%; display: block; margin:auto;"
                         src="https://millionstatusov.ru/pic/statpic/all/58e61335ec518.jpg" data-holder-rendered="true">
                    <div class="card-body">
                        <div style="max-height:180px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">
                            <p class="card-text">{{ item.mainText|safe }}</p>
                        </div>
                        {% for articletag in item.tag_set.all %}
                        <div class="tag">
                            <a href="/categoryView/{{tag.text}}/"><span class="label label-info">{{ articletag.text }}</span></a>
                        </div>
                        {% endfor %}
                        <br>
                        <br>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">{% trans "комментировать" %}</button>
                            </div>
                            <small class="text-muted">{{item.creationDate}}</small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% endfor %}
    {% endif %}
    {% endblock %}